"""initial schema

Revision ID: 23670b97ba39
Revises: 
Create Date: 2026-03-26 00:12:11.536123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23670b97ba39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('search_instructions', sa.Text(), nullable=True),
    sa.Column('num_videos', sa.Integer(), nullable=False),
    sa.Column('min_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('channel_type_filters', sa.Text(), nullable=True),
    sa.Column('channel_list', sa.Text(), nullable=True),
    sa.Column('videos_per_channel', sa.Integer(), nullable=True),
    sa.Column('chroma_collection_name', sa.String(length=100), nullable=True),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_exchanges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('channel_name', sa.String(length=200), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('transcript_status', sa.String(length=20), nullable=False),
    sa.Column('transcript_word_count', sa.Integer(), nullable=True),
    sa.Column('transcript_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('qa_exchanges')
    op.drop_table('jobs')
    # ### end Alembic commands ###
